print('嗨喽，世界')
print('你的名字！')
myName = input()
print('很高兴见到你，'+ myName)
print('你的名字长度：')
print(len(myName))
print('你的年龄是？')
myAge = input()
print('你大学一年级是多少年？')
myYear = input()
z = myAge + myYear
print('你将来会在一年后变成'+ str(int(myAge)+1) + '岁。')
print('你将会在'+str(4-(2020-int(myYear)))+'年后毕业。')
print("myAge+myYear=",z)
print("myAge+myYear="+z)
